"""Panther Labs `pypanther` rule parser (issue #27).

pypanther is Panther's newer Pythonic detection framework: rules are
pure Python classes (no YAML sibling) under `pypanther/rules/<vendor>/`:

    @panther_managed
    class AWSCloudTrailStopped(Rule):
        id = "AWS.CloudTrail.Stopped-prototype"
        display_name = "CloudTrail Stopped"
        log_types = [LogType.AWS_CLOUDTRAIL]
        tags = ["AWS", "Security Control"]
        reports = {"CIS": ["3.5"], "MITRE ATT&CK": ["TA0005:T1562"]}
        default_severity = Severity.MEDIUM
        ...
        def rule(self, event): ...

Metadata comes from CLASS ATTRIBUTES, extracted via ast walking — the
modules are never imported (helper imports would execute). The whole
module source is surfaced verbatim as `detection_logic`, mirroring the
`panther` source.

`LogType.AWS_CLOUDTRAIL` enum members resolve to their string values
("AWS.CloudTrail") via `pypanther/log_types.py`, an autogenerated
str-Enum the sparse checkout includes — so taxonomy resolution reuses
the panther-analysis mapping unchanged. Unresolvable members fall back
to the attribute name verbatim (better a fingerprintable miss than a
dropped rule).

MITRE tags use the same `TA####:T####` colon-joined shape as
panther-analysis; split into canonical tactics + techniques here.
"""

import ast
import logging
from pathlib import Path
from typing import Any, Optional

from app.parsers.base import BaseParser, ParsedRule
from app.parsers.panther import _PANTHER_MITRE_RE
from app.services.rule_discovery import RuleDiscoveryService

logger = logging.getLogger(__name__)

_LOG_TYPES_MODULE = Path("pypanther/log_types.py")

# Class attributes we lift into metadata.
_SEVERITY_DEFAULT = "medium"


class PyPantherParser(BaseParser):
    """Parser for Panther Labs pypanther framework rules."""

    def __init__(self, discovery: Optional[RuleDiscoveryService] = None):
        self.discovery = discovery
        # LogType attr name -> string value ("AWS_CLOUDTRAIL" ->
        # "AWS.CloudTrail"). Lazy-loaded from the sparse-checked-out
        # enum module; empty when unavailable (tests, missing file).
        self._log_type_map: Optional[dict[str, str]] = None

    @property
    def source_name(self) -> str:
        return "pypanther"

    def can_parse(self, file_path: Path) -> bool:
        path_str = str(file_path).lower().replace("\\", "/")
        if not path_str.endswith(".py"):
            return False
        if "pypanther/rules/" not in path_str:
            return False
        name = path_str.rsplit("/", 1)[-1]
        return name != "__init__.py"

    # ── LogType enum resolution ────────────────────────────────────

    def _log_types(self) -> dict[str, str]:
        if self._log_type_map is not None:
            return self._log_type_map
        self._log_type_map = {}
        if self.discovery is not None:
            try:
                content = self.discovery.get_rule_content(
                    "pypanther", _LOG_TYPES_MODULE
                )
                if content:
                    self._log_type_map = self._parse_log_type_enum(content)
            except Exception as exc:  # pragma: no cover - defensive
                logger.warning(f"pypanther LogType enum unavailable: {exc}")
        return self._log_type_map

    @staticmethod
    def _parse_log_type_enum(source: str) -> dict[str, str]:
        """ATTR = "String.Value" assignments inside `class LogType`."""
        out: dict[str, str] = {}
        try:
            tree = ast.parse(source)
        except SyntaxError:
            return out
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef) and node.name == "LogType":
                for stmt in node.body:
                    if (
                        isinstance(stmt, ast.Assign)
                        and len(stmt.targets) == 1
                        and isinstance(stmt.targets[0], ast.Name)
                        and isinstance(stmt.value, ast.Constant)
                        and isinstance(stmt.value.value, str)
                    ):
                        out[stmt.targets[0].id] = stmt.value.value
        return out

    # ── Attribute value extraction ─────────────────────────────────

    def _attr_value(self, node: ast.AST) -> Any:
        """Literal-ish value of a class-attribute assignment."""
        if isinstance(node, ast.Constant):
            return node.value
        if isinstance(node, (ast.List, ast.Tuple, ast.Set)):
            return [self._attr_value(el) for el in node.elts]
        if isinstance(node, ast.Dict):
            return {
                self._attr_value(k): self._attr_value(v)
                for k, v in zip(node.keys, node.values)
                if k is not None
            }
        if isinstance(node, ast.Attribute):
            # LogType.AWS_CLOUDTRAIL -> "AWS.CloudTrail" (enum value),
            # Severity.MEDIUM -> "MEDIUM" (attr name).
            base = node.value
            if isinstance(base, ast.Name) and base.id == "LogType":
                return self._log_types().get(node.attr, node.attr)
            return node.attr
        return None

    @staticmethod
    def _is_rule_class(node: ast.ClassDef) -> bool:
        for b in node.bases:
            name = b.id if isinstance(b, ast.Name) else (
                b.attr if isinstance(b, ast.Attribute) else ""
            )
            if name.endswith("Rule"):
                return True
        return False

    # ── Parse ──────────────────────────────────────────────────────

    def parse(self, file_path: Path, content: str) -> Optional[ParsedRule]:
        try:
            tree = ast.parse(content)
        except SyntaxError as exc:
            logger.warning(f"pypanther syntax error in {file_path}: {exc}")
            return None

        rule_class: Optional[ast.ClassDef] = None
        for node in tree.body:
            if isinstance(node, ast.ClassDef) and self._is_rule_class(node):
                rule_class = node
                break
        if rule_class is None:
            # Helper module inside rules/ — not a rule.
            return None

        attrs: dict[str, Any] = {}
        for stmt in rule_class.body:
            if isinstance(stmt, ast.Assign) and len(stmt.targets) == 1 and isinstance(stmt.targets[0], ast.Name):
                attrs[stmt.targets[0].id] = self._attr_value(stmt.value)
            elif isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name) and stmt.value is not None:
                attrs[stmt.target.id] = self._attr_value(stmt.value)

        rule_id = attrs.get("id")
        if not isinstance(rule_id, str) or not rule_id:
            # A Rule subclass without an id is an abstract/base helper.
            return None

        title = attrs.get("display_name") or rule_class.name

        log_types = [
            lt for lt in (attrs.get("log_types") or [])
            if isinstance(lt, str) and lt
        ]

        tags = [t for t in (attrs.get("tags") or []) if isinstance(t, str)]

        # MITRE from reports {"MITRE ATT&CK": ["TA0005:T1562", ...]}
        tactics: list[str] = []
        techniques: list[str] = []
        reports = attrs.get("reports") or {}
        if isinstance(reports, dict):
            for family, entries in reports.items():
                if not isinstance(entries, list):
                    continue
                if str(family).upper().replace("&", "").replace(" ", "") in (
                    "MITREATTCK", "MITREATTACK",
                ):
                    for entry in entries:
                        m = _PANTHER_MITRE_RE.match(str(entry))
                        if m:
                            if m.group(1) not in tactics:
                                tactics.append(m.group(1))
                            if m.group(2) not in techniques:
                                techniques.append(m.group(2))
                else:
                    fam_slug = str(family).strip().lower().replace(" ", "_")
                    tag = f"report:{fam_slug}"
                    if tag not in tags:
                        tags.append(tag)

        severity = attrs.get("default_severity")
        severity = severity.lower() if isinstance(severity, str) else _SEVERITY_DEFAULT

        description = attrs.get("default_description")
        if not isinstance(description, str):
            description = ""

        reference = attrs.get("default_reference")
        runbook = attrs.get("default_runbook")

        # `enabled = False` classes ship disabled upstream.
        status = "experimental" if attrs.get("enabled") is False else "stable"

        log_source = {
            "product": (
                log_types[0].split(".", 1)[0].lower() if log_types else None
            ),
            "service": None,
            "category": None,
        }

        return ParsedRule(
            source=self.source_name,
            file_path=str(file_path),
            raw_content=content,
            title=str(title),
            description=description.strip(),
            author=None,
            status=status,
            severity=severity,
            log_source=log_source,
            tags=tags,
            mitre_attack={
                "tactics": tactics,
                "techniques": techniques,
                "groups": [],
                "software": [],
            },
            detection_logic_raw=content,
            false_positives=[runbook] if isinstance(runbook, str) and runbook else [],
            extra={
                "id": rule_id,
                "language": "python",
                "log_types": log_types,
                "analysis_type": "rule",
                "reference": reference,
                "runbook": runbook,
                "class_name": rule_class.name,
                "threshold": attrs.get("threshold"),
                "dedup_period_minutes": attrs.get("dedup_period_minutes"),
            },
        )
